version: '3'

services:
  am-org-role-mapping-batch-service:
    build:
      context: .
    image: hmcts/am-org-role-mapping-batch-service
    container_name: am-org-role-mapping-batch-service
    ports:
      - ${SERVER_PORT:-4080}:${SERVER_PORT:-4080}
    environment:
      - ORG_ROLE_MAPPING_SERVICE_POSTGRES_HOST=am-org-role-mapping-database
      - ORG_ROLE_MAPPING_SERVICE_POSTGRES_DATABASE=org_role_mapping
      - ORG_ROLE_MAPPING_SERVICE_POSTGRES_PORT=5432
      - ORG_ROLE_MAPPING_SERVICE_POSTGRES_USER=orm
      - ORG_ROLE_MAPPING_SERVICE_POSTGRES_PASS=orm
      - POSTGRES_HOST_AUTH_METHOD=trust