job:
  image: 'hmctspublic.azurecr.io/am/org-role-mapping-batch-service:latest'
  ingressHost: am-org-role-mapping-batch-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  applicationPort: 4080
  aadIdentityName: am
  kind: CronJob
  schedule: "*/10 * * * *"
global:
  jobKind: CronJob
postgres:
  enabled: false